FROM node:10

WORKDIR /src

COPY ./package.json ./package-lock.json /src/


RUN npm install
RUN npm install pm2 -g
# RUN npm install pm2 -g
COPY . /src

# Expose the port the app runs in
EXPOSE 1024

CMD ["npm","run","start:dev"]
